routes/web.php
<?php

use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\ActivityModelController;
use App\Http\Controllers\SubactivityController;
use App\Http\Controllers\DataController;
use App\Http\Controllers\DataMultipleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return view('auth.login');      
});


/*Route::get('/login',function(){
return view('auth.login');
})->middleware('verified')->name('login');*/


Route::get('/login',[LoginController::class,'index'])->name('login');
Route::post('/login',[LoginController::class,'store']);
Route::get('/logout',[LoginController::class,'logout'])->name('logout');

Route::get('/register',[RegisterController::class,'index'])->name('register');
Route::post('/register',[RegisterController::class,'store']);

Route::group(['middleware'=>'auth'],function(){ 

//prefix('activity-model')->name('activity.model.')->
Route::group(['prefix'=>'activity-model','as'=>'activity.model.'],function(){
Route::get('/add',[ActivityModelController::class,'create'])->name('add');
Route::post('/add',[ActivityModelController::class,'store']);
Route::get('/edit/{id}',[ActivityModelController::class,'edit'])->name('edit');
Route::post('/edit/{id}',[ActivityModelController::class,'update']);
Route::delete('/delete/{acm}',[ActivityModelController::class,'destroy'])->name('delete');
//Route::get('/list/{user}',[ActivityModelController::class,'index'])->name('activity.model.list');
Route::get('/list',[ActivityModelController::class,'index'])->name('list');
Route::post('/set-status-acm',[ActivityModelController::class,'setStatusActivityModel'])->name('set.status.acm');
});

//prefix('subactivity')->name('subactivity.')->
Route::group(['prefix'=>'subactivity','as'=>'subactivity.'],function(){
    Route::get('/add',[SubactivityController::class,'create'])->name('add');
    Route::post('/add',[SubactivityController::class,'store']);
    Route::get('/list',[SubactivityController::class,'index'])->name('list');
    Route::get('/edit/{subactivity}',[SubactivityController::class,'edit'])->name('edit');
    Route::post('/edit/{subactivity}',[SubactivityController::class,'update']);
    Route::delete('/delete/{subactivity}',[SubactivityController::class,'destroy'])->name('delete');
    Route::post('/set-status-subact/{subactivity?}',[SubactivityController::class,'setStatusSubActivity'])->name('set.status.subact');
});

Route::group(['prefix'=>'data','as'=>'data.'],function(){
    
    Route::get('/{activityModelID}/list',[DataController::class,'index'])->name('list');
    Route::get('/{activityModelID}/add',[DataController::class,'create'])->name('add');
    Route::post('/{activityModelID}/add',[DataController::class,'store'])->name('store');
    Route::get('/{activityModelID}/edit/{data}',[DataController::class,'edit'])->name('edit');
    Route::post('/{activityModelID}/edit/{data}',[DataController::class,'update']);
    //Route::delete('/delete/{data}',[DataController::class,'destroy'])->name('delete');
    
});

Route::group(['prefix'=>'data-multiple','as'=>'data.multiple.'],function(){

    Route::get('/{count}/add',[DataMultipleController::class,'create'])->name('add');
    Route::post('/{count}/add',[DataMultipleController::class,'store']);
    Route::get('/{count}/list',[DataMultipleController::class,'index'])->name('list');

});

});



Route::get('/forgot-password',function(){
    return view('pages.forgot');
})->name('forgot.password');

//Auth::route(['verify'=>true]);

Route::get('/dashboard',function(){    
    return view('layouts.master');
})->middleware('auth');


 Route::get('email/verify/{id}/{hash}', 'Auth\VerificationController@verify')->name('verification.verify');

 //Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');

app/Models/ActivityModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class ActivityModel extends Model
{
    use SoftDeletes;
    protected $fillable = [
       'am_type','activity_model' 
    ];
    
    public function ownedBy(User $user){
      return $user->id == $this->user_id;
    }

    public function subactivitiesMapSingle($acm_id){
        /*return $this->hasMany(Subactivity_map::class)
                    ->select('subactivity_id',\DB::raw('COUNT(*) as c'))
                    ->where('actives',1)
                    //->where('activity_model_id',$acm_id)
                    ->groupBy('subactivity_id')
                    ->having('c', '=' , 1);*/
    }

    public function singleAcmModelsSubActivities($am_type=1){
        /*return $this->hasManyThrough(Subactivity_map::class)->select(\DB::raw('COUNT(*) as c'))
                    ->where('subactivity.am_type',$am_type)
                    ->where('subactivity.active',1)
                    ->where('subactivity_map.active',1)
                    ->groupBy('subactivity_id')
                    ->having('c', '=' , 1);*/
                    
    }
    
}

app/Http/Controllers/ActivityModelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Models\ActivityModel;
use App\Models\User;
use App\Models\Subactivity_map;
use DB;

class ActivityModelController extends Controller
{

    private function validate_acm($request){
        $rules = [
            'am_type'=>'required|in:1,2',
            'activity_model'=>['required','string','min:2','max:20',
            Rule::unique('activity_models')->where(function($query) use ($request) {               
                $condition = [
                    'am_type'=>$request->am_type,
                    'user_id'=>auth()->user()->id,
                    'deleted_at'=>NULL
                 ]; 
                return $query->where($condition)->where('id','!=',$request->id);

            })

            ]
        ];

        $attributes = ['am_type'=>'Actiivty Model Type'];

        $this->validate($request,$rules,[],$attributes);
    }
    public function index(){

        /*dd(Subactivity_map::selectRaw('count(subactivity_id) as sub')->groupBy('subactivity_id')
            ->having('sub',1)
            ->get());*/



        $activity_models = auth()->user()->activityModels()->get();
        return view('activity_model.list',compact('activity_models'));
    }
    public function create(){
        $action_route = route('activity.model.add');
        return view('activity_model.add',compact('action_route'));
    }

    public function store(Request $request){
        
        $this->validate_acm($request);
        $ac = auth()->user()->activityModels()->create($request->only('am_type','activity_model'));


        if($ac->save()){
        return redirect()->route('activity.model.list')->with('message','Activity model created successfully.');
        }
        
    }

    public function edit($id){
        $acm = ActivityModel::find($id);
        $action_route = route('activity.model.edit',$id);
        return view('activity_model.add',compact('acm','action_route'));
    }

    public function update(Request $request,$id){
        $this->validate_acm($request);   

        $acm = ActivityModel::find($id);

        $acm->activity_model = $request->activity_model;
        $acm->am_type = $request->am_type;
        $acm->updated_by = auth()->user()->id;
        
        if($acm->save()){
        return redirect()->route('activity.model.list')->with('message','Activity model updated successfully.');
        }
        
    }

    public function destroy(ActivityModel $acm){
        
        $acm_name = $acm->activity_model;
        
        $acm->delete();

        return back()->with('swal_delete','Activity model deleted successfully');
    }

    public function setStatusActivityModel(Request $request){
        $acm = ActivityModel::where('id',$request->_id)
                       ->update(['active'=>$request->status,'updated_by'=>auth()->user()->id]);

        $staus_label = $request->status == 1 ? 'actived' : 'deactived';
        $message = $acm ?
                    ['icon'=>'success','message'=>'Activity model '.$staus_label.' successfully.'] : 
                    ['icon'=>'error','message'=>'Error updating status'] ;

        return response()->json($message);
    }
}

resources/views/activity_model/add.blade.php
@extends('layouts.master')

@section('content')
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Acitivity Model</h1>
                    </div>

                    <div class="row">

                        <div class="col-lg-9">

                            <!-- Basic Card Example -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Activity Model Form</h6>
                                </div>
                                <div class="card-body">
                                 <form action="{{ $action_route }}" method="post">
 <fieldset class="form-group row">
    <legend class="col-form-label col-sm-3 float-sm-left pt-0">Acitivity Model Type</legend>
    <div class="col-sm-9">
      <div class="form-check">
        @csrf
        <input class="form-check-input" type="radio" name="am_type" id="gridRadios1" value="1" {{ old('am_type',$acm->am_type ?? '')==1?'checked':'' }}>
        <label class="form-check-label" for="gridRadios1">
          Todo
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="am_type" id="gridRadios2" value="2" {{ old("am_type",$acm->am_type ?? '')==2?"checked":"" }}>
        <label class="form-check-label" for="gridRadios2">
          Not Todo
        </label>
      </div>
      @error('am_type')
      <div class="invalid-feedback d-block">
      {{ $message }}
      </div>
      @enderror
    </div>
  </fieldset>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-3 col-form-label">Acitivity Model Name</label>
    <div class="col-sm-9">
      <input type="text" name="activity_model" class="form-control @error('activity_model') is-invalid @enderror" id="inputEmail3" placeholder="Type Acitivity Model Name here..." value="{{ old('activity_model',$acm->activity_model ?? '' )}}">
      @error('activity_model')
      <div class="invalid-feedback d-block">
          {{$message}}
      </div>
     @enderror
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-3"></label>
    <div class="col-sm-9">
      <button type="submit" class="btn btn-primary">Submit</button>
      <button type="submit" class="btn btn-danger">Cancel</button>
    </div>
  </div>
</form>
                                </div>
                            </div>

                        </div>

                    </div>
@endsection('content')

resources/views/activity_model/list.blade.php
@extends('layouts.master')

@section('content')
    

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Acitivity Model</h1>



                    </div>

                    <div class="row">

                                 <div class="col-lg-12">
                                       @if(session('message'))
                          <div class="alert alert-success"> 
                          {{ session('message') }}
                          </div>
                          @endif
                            <!-- Dropdown Card Example -->
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div
                                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                    <h6 class="m-0 font-weight-bold text-primary">Activit Models List</h6>
                                    <div class="dropdown no-arrow">
                                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                                            aria-labelledby="dropdownMenuLink">
                                            <div class="dropdown-header">ACM actions:</div>
                                            <a class="dropdown-item" href="{{ route('activity.model.add') }}">
                                            <i class="fas fa-plus"></i>
                                            Add New
                                            </a>
                                            <a class="dropdown-item" href="#">
                                            <i class="fas fa-sort"></i>
                                            Set sorting
                                            </a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">
                                            <i class="fas fa-times"></i>
                                            Close
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <!-- Card Body -->
                                <div class="card-body">
                                      <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Serial #</th>
                                            <th>Name</th>
                                            <th>AM Type</th>
                                            <th>Status</th>
                                            <th>Created at</th>
                                            <th>Actions</th>
                                        </tr> 
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Serial #</th>
                                            <th>Name</th>
                                            <th>AM Type</th>
                                            <th>Status</th>
                                            <th>Created at</th>
                                            <th>Actions</th>
                                        </tr>
                                    </tfoot>
                                      <tbody>
                                          @foreach($activity_models as $key=>$ac)
                                          <tr>
                                          <td>{{ ++$key }}</td>
                                          <td>{{ $ac->activity_model }}</td>
                                          <td>
                                            {!! $ac->am_type==1 ? '<span class="badge badge-success">Todo</span>' : '<span class="badge badge-danger">Not Todo</span>'  !!}
                                          </td>
                                          <td>
                                            <input type="checkbox" class="bs-switch" _id="{{ $ac->id }}" data-onstyle="success" data-toggle="toggle" data-on="Active" data-off="Deactive" data-size="xs" @php echo $ac->active==1?'checked':''; @endphp >
                                          </td>
                                          <td>
                                            {{ date('M-d h:i:s A',strtotime($ac->created_at))  }}
                                          </td>
                                          <td>  
                                            <a href="{{ route('activity.model.edit',$ac->id) }}" class='btn btn-primary'>
                                              <i class="fas fa-edit"></i>
                                              Edit
                                            </a>
                                            <form method="post" action="{{ route('activity.model.delete',$ac)}}" style="display: inline;">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class='btn btn-danger delete-acm'>
                                              <i class="fas fa-trash"></i>
                                              Delete
                                            </button>
                                            </form>
                                          </td>
                                          </tr>
                                          @endforeach
                                      </tbody>
                                </table>
                            </div>
                                </div>
                            </div>

                        </div>

                    </div>

              

@endsection('content')

@push('scripts')
<script src="{{ asset('assets/js/custom/activity_model/list.js') }}"></script>
    <script type="text/javascript">
        GLOBAL_VARS.services['set_status_acm'] = '{{ route('activity.model.set.status.acm') }}'
         @if(session('swal_delete'))
          swal('{{ @session('swal_delete') }}', {
          icon: "success",
          });
         @endif
    </script>
@endpush