routes/web.php
<?php

use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\ActivityModelController;
use App\Http\Controllers\SubactivityController;
use App\Http\Controllers\DataController;
use App\Http\Controllers\DataMultipleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   return view('auth.login');      
});


/*Route::get('/login',function(){
return view('auth.login');
})->middleware('verified')->name('login');*/


Route::get('/login',[LoginController::class,'index'])->name('login');
Route::post('/login',[LoginController::class,'store']);
Route::get('/logout',[LoginController::class,'logout'])->name('logout');

Route::get('/register',[RegisterController::class,'index'])->name('register');
Route::post('/register',[RegisterController::class,'store']);

Route::group(['middleware'=>'auth'],function(){ 

//prefix('activity-model')->name('activity.model.')->
Route::group(['prefix'=>'activity-model','as'=>'activity.model.'],function(){
Route::get('/add',[ActivityModelController::class,'create'])->name('add');
Route::post('/add',[ActivityModelController::class,'store']);
Route::get('/edit/{id}',[ActivityModelController::class,'edit'])->name('edit');
Route::post('/edit/{id}',[ActivityModelController::class,'update']);
Route::delete('/delete/{acm}',[ActivityModelController::class,'destroy'])->name('delete');
//Route::get('/list/{user}',[ActivityModelController::class,'index'])->name('activity.model.list');
Route::get('/list',[ActivityModelController::class,'index'])->name('list');
Route::post('/set-status-acm',[ActivityModelController::class,'setStatusActivityModel'])->name('set.status.acm');
});

//prefix('subactivity')->name('subactivity.')->
Route::group(['prefix'=>'subactivity','as'=>'subactivity.'],function(){
    Route::get('/add',[SubactivityController::class,'create'])->name('add');
    Route::post('/add',[SubactivityController::class,'store']);
    Route::get('/list',[SubactivityController::class,'index'])->name('list');
    Route::get('/edit/{subactivity}',[SubactivityController::class,'edit'])->name('edit');
    Route::post('/edit/{subactivity}',[SubactivityController::class,'update']);
    Route::delete('/delete/{subactivity}',[SubactivityController::class,'destroy'])->name('delete');
    Route::post('/set-status-subact/{subactivity?}',[SubactivityController::class,'setStatusSubActivity'])->name('set.status.subact');
});

Route::group(['prefix'=>'data','as'=>'data.'],function(){
    
    Route::get('/{activityModelID}/list',[DataController::class,'index'])->name('list');
    Route::get('/{activityModelID}/add',[DataController::class,'create'])->name('add');
    Route::post('/{activityModelID}/add',[DataController::class,'store'])->name('store');
    Route::get('/{activityModelID}/edit/{data}',[DataController::class,'edit'])->name('edit');
    Route::post('/{activityModelID}/edit/{data}',[DataController::class,'update']);
    //Route::delete('/delete/{data}',[DataController::class,'destroy'])->name('delete');
    
});

Route::group(['prefix'=>'data-multiple','as'=>'data.multiple.'],function(){

    Route::get('/{count}/add',[DataMultipleController::class,'create'])->name('add');
    Route::post('/{count}/add',[DataMultipleController::class,'store']);
    Route::get('/{count}/list',[DataMultipleController::class,'index'])->name('list');

});

});



Route::get('/forgot-password',function(){
    return view('pages.forgot');
})->name('forgot.password');

//Auth::route(['verify'=>true]);

Route::get('/dashboard',function(){    
    return view('layouts.master');
})->middleware('auth');


 Route::get('email/verify/{id}/{hash}', 'Auth\VerificationController@verify')->name('verification.verify');

 //Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');

app/Models/Subactivity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

class Subactivity extends Model
{
    use SoftDeletes;
    
    protected $table = 'subactivity';
        //activity_model_id
    protected $fillable = [
        'am_type','subactivity','frequency_type','frequency_per_day','frequency'
    ];
    
    public function activityModels()
    {   
        return $this->belongsToMany(ActivityModel::class,Subactivity_map::class);    
    }
    
     public function subactivitiesMap()
    {   
        return $this->hasMany(Subactivity_map::class);    
    }
}

app/Http/Controllers/SubactivityController.php
<?php

namespace App\Http\Controllers;

use App\Models\Subactivity;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Models\User;    
use App\Models\Subactivity_map;

use DB;

class SubactivityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
          DB::enableQueryLog(); 
        $acms = auth()->user()->activityModels()->get();

        $subacts = auth()->user()->subactivities()->latest()->with(['activityModels'=>function($query){
            $query->where('subactivity_map.active',1);  
        }]);

        

        $subacts->when(request('subactivity'),function($query){
            $subactivity = request('subactivity');
            $query->where('subactivity','like','%'.$subactivity.'%');
        });

        $subacts->when(request('activity_model'),function($query){
            $acm_ids = request('activity_model');
            $query->where('subactivity','like','%'.request('subactivity').'%');
        });

        $subacts = $subacts->paginate(10);
        //$subacts->paginate(10);
            
    //    dd($subacts);
        //dd($subacts->toArray());
            $dr = DB::getQueryLog();

            //dd($dr);
        return view('subactivity.list',compact('acms','subacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    { 
        $acms = auth()->user()->activityModels()->latest()->where('active',1)->get();
        $action_route = route('subactivity.add');
        return view('subactivity.add',compact('action_route','acms'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function subactivity_validations($request,$subactivity_id=NULL){
            
        $rules = [
            'am_type'=>'required|in:1,2',
            'activity_model_id'=>'required',
            'subactivity'=>['required','min:2','max:20',
             Rule::unique('subactivity')->where(function($query) use ($request,$subactivity_id) {
                $query->where(['am_type'=>$request->am_type,'user_id'=>auth()->user()->id]);
                
                if($subactivity_id){
                    $query->where('id','!=',$subactivity_id);
                }

             })->whereNull('deleted_at')
            ],
            'frequency_type'=>'required|in:1,2,3,4',
            'frequency_per_day'=>'required|in:1,2',
            /*'frequency' => Rule::requiredIf(function () use ($request) {
            return $request->frequency_per_day==2;
            })*/
            'frequency'=>$request->frequency_per_day==2 ? 'required' : ''
        ];

       /* if($subactivity_id){
            $rules['subactivity'][] = Rule::unique('subactivity_map')->where(function($query) use ($subactivity_id){
                $query->where(['subactivity_id'=>$subactivity])
            });
        }*/

        $attributes = [
            'am_type'=>'activity model type',
            'frequency_type'=>'frequency type'
        ];

        $this->validate($request,$rules,[],$attributes);
    }
    public function store(Request $request)
    {
        $this->subactivity_validations($request);

        $save = auth()->user()->subactivities()->create($request->only('am_type','subactivity','frequency_type','frequency_per_day','frequency'));

        $subactivity_id = $save->id;

        $acm_ids = $request->activity_model_id;

        $subactivity_map_arr = array_map(function($acm_id) use ($subactivity_id) {
            
            return [
                'activity_model_id'=>$acm_id,
                'subactivity'=>$subactivity_id,
            ];

        } , $acm_ids);

        //dd($subactivity_map_arr);

       $save->subactivitiesMap()->createMany($subactivity_map_arr);



        if($save){
            return redirect()->route('subactivity.list')->with('message','Subactivity created successfully.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Subactivity  $subactivity
     * @return \Illuminate\Http\Response
     */
    public function show(Subactivity $subactivity)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Subactivity  $subactivity
     * @return \Illuminate\Http\Response
     */
    public function edit(Subactivity $subactivity)
    {
     $acms = auth()->user()->activityModels()->latest()->where('active',1)->get();
     $action_route = route('subactivity.edit',$subactivity); 
     $subactivity = $subactivity->where('id',$subactivity->id)->with(['activityModels'])->first();
     //$selected_acms = $subactivity->activityModels->pluck('id')->toArray();
     $selected_acms = $subactivity->subactivitiesMap()->where('active',1)->pluck('activity_model_id')->toArray();    

     return view('subactivity.add',compact('action_route','acms','subactivity','selected_acms'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Subactivity  $subactivity
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subactivity $subactivity)
    {
        $this->subactivity_validations($request,$subactivity->id);

        $subactivity->am_type = $request->am_type;
    //    $subactivity->activity_model_id = $request->activity_model_id;
        $subactivity->subactivity = $request->subactivity;
        $subactivity->frequency_type = $request->frequency_type;
        $subactivity->frequency_per_day = $request->frequency_per_day;
        $subactivity->frequency = $request->frequency;


        $subactivity_id = $subactivity->id;

        $acm_ids = $request->activity_model_id;

        $acms_ids_exist = $subactivity->activityModels->pluck('id')->toArray();

        $acm_ids_arr = array_diff($acm_ids,$acms_ids_exist);

        $acm_ids_disable = array_diff($acms_ids_exist,$acm_ids);

        $subactivity_map_arr = array_map(function($acm_id) use ($subactivity_id) {

            return [
                'activity_model_id'=>$acm_id,
                'subactivity'=>$subactivity_id,
            ];

        } , $acm_ids_arr);  

        $subactivities_map = $subactivity->subactivitiesMap();

        $remove_ids = $subactivities_map
                                   ->whereIn('activity_model_id',$acm_ids_disable)
                                   ->get()->pluck('id')->toArray();


        $save = $subactivity->save();
        $subactivities_map->createMany($subactivity_map_arr);
        $subactivities_map->whereIn('id',$remove_ids)->update(['active'=>0]);

        if($save){
            return redirect()->route('subactivity.list')->with('message','Subactivity updated successfully.');
        }
    }   

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Subactivity  $subactivity
     * @return \Illuminate\Http\Response
     */
    public function destroy(Subactivity $subactivity)
    {
        $subactivity->delete();

        return back()->with('swal_delete','Subactivity deleted successfully.');
    }

    public function setStatusSubActivity(Request $request,Subactivity $subactivity){
            $subactivity->active = $request->status;
            $subactivity->updated_by = auth()->user()->id;

            $save = $subactivity->save();

             $staus_label = $request->status == 1 ? 'actived' : 'deactived';
             $message = $save ?
                    ['icon'=>'success','message'=>$subactivity->subactivity.' '.$staus_label.' successfully.'] : 
                    ['icon'=>'error','message'=>'Error updating status'] ;

            return response()->json($message);
    }
}

resources/views/subactivity/add.blade.php
@extends('layouts.master')

@section('content')

@php
//dd($subactivity->toArray());
//var_dump(old('activity_model_id'));exit;    
 @endphp

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Subactivty</h1>
                    </div>

                    <div class="row">

                        <div class="col-lg-9">

                            <!-- Basic Card Example -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Subactivty Form</h6>
                                </div>
                                <div class="card-body">
                                 <form action="{{ $action_route }}" method="post">
 <fieldset class="form-group row">
    <legend class="col-form-label col-sm-3 float-sm-left pt-0">Activity Model Type</legend>
    <div class="col-sm-9">
      <div class="form-check">
        @csrf
        <input class="form-check-input" type="radio" name="am_type" id="radio1" value="1" 
        {{ old('am_type',$subactivity->am_type ?? '')==1 ? 'checked':'' }}
        >
        <label class="form-check-label" for="radio1">
          Todo
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="am_type" id="radio2" value="2"
        {{ old('am_type',$subactivity->am_type ?? '')==2 ? 'checked':'' }}
        >
        <label class="form-check-label" for="radio2">
          Not Todo
        </label>
      </div>
      @error('am_type')
      <div class="invalid-feedback d-block">
      {{ $message }}
      </div>
      @enderror
    </div>
  </fieldset>
   <div class="form-group row">
    <label for="inputEmail3" class="col-sm-3 col-form-label">Actvity Models Selection</label>
    <div class="col-sm-9">
      <!-- <input type="text" name="activity_model" class="form-control @error('activity_model') is-invalid @enderror" id="inputEmail3" placeholder="Type Acitivity Model Name here..." value="{{ old('activity_model',$acm->activity_model ?? '' )}}"> -->

      <select class="form-control" id="acms_dd" {{ old('am_type',$subactivity->am_type ?? '') =='' ? 'disabled':''}} multiple name="activity_model_id[]">
          <option value=""></option>

          @foreach($acms as $key=>$acm)
          <!-- {{ old('activity_model_id'.$key,$subactivity->activity_model_id ?? '')==$acm->id ? 'selected' : '' }}  -->
          <option 

            {{ in_array($acm->id,old('activity_model_id',$selected_acms ?? [])) ? 'selected' : '' }}
            value="{{ $acm->id }}" am_type="{{ $acm->am_type }}" style="display:{{ old('am_type',$subactivity->am_type ?? '')==1 && $acm->am_type!=1 ? 'none' : (old('am_type',$subactivity->am_type ?? '')==2 && $acm->am_type!=2 ? 'none': '')  }}"> {{ $acm->activity_model }} </option>
            }
          @endforeach
      </select>

      @if($errors->has('activity_model_id'))
      <div class="invalid-feedback d-block">
        Activity Model is required
      </div>
     @endif
    </div>
  </div>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-3 col-form-label">Subactivity Name</label>
    <div class="col-sm-9">
      <input type="text" name="subactivity" class="form-control @error('subactivity') is-invalid @enderror" id="inputEmail3" placeholder="Type Subactivty Name here..." value="{{ old('subactivity',$subactivity->subactivity ?? '') }}">
      @error('subactivity')
      <div class="invalid-feedback d-block">
          {{$message}}
      </div>
     @enderror
    </div>
  </div>

   <fieldset class="form-group row">
    <legend class="col-form-label col-sm-3 float-sm-left pt-0">Frequency Type</legend>
    <div class="col-sm-9">
      <div class="form-check">
        
        <input class="form-check-input" type="radio" name="frequency_type" id="gridRadios3" value="1"
        {{ old('frequency_type',$subactivity->frequency_type ?? '')==1 ? 'checked' : '' }}
        >
        <label class="form-check-label" for="gridRadios3">
          Daily
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="frequency_type" id="gridRadios4" value="2"
        {{ old('frequency_type',$subactivity->frequency_type ?? '')==2 ? 'checked' : '' }}
        >
        <label class="form-check-label" for="gridRadios4">
          Weekly
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="frequency_type" id="radio5" value="3"
        {{ old('frequency_type',$subactivity->frequency_type ?? '')==3 ? 'checked' : '' }}
        >
        <label class="form-check-label" for="radio5">
          Monthly
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="frequency_type" id="radio6" value="4"
        {{ old('frequency_type',$subactivity->frequency_type ?? '')==4 ? 'checked' : '' }}
        >
        <label class="form-check-label" for="radio6">
          Custom
        </label>
      </div>
      @error('frequency_type')
      <div class="invalid-feedback d-block">
      {{ $message }}
      </div>
      @enderror
    </div>
  </fieldset>

   <fieldset class="form-group row">
    <legend class="col-form-label col-sm-3 float-sm-left pt-0">Frequency Per Day</legend>
    <div class="col-sm-9">
      <div class="form-check">
        
        <input class="form-check-input" type="radio" name="frequency_per_day" id="radio7" value="1"
        {{ old('frequency_per_day',$subactivity->frequency_per_day ?? '')==1 ? 'checked' : '' }}
        >
        <label class="form-check-label" for="radio7">
          Once
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="frequency_per_day" id="radio8" value="2"
        {{ old('frequency_per_day',$subactivity->frequency_per_day ?? '')==2 ? 'checked' : '' }}
        >
        <label class="form-check-label" for="radio8">
          More than once
        </label>
      </div>
      @error('frequency_per_day')
      <div class="invalid-feedback d-block">
      {{ $message }}
      </div>
      @enderror
    </div>
  </fieldset>
  
  <div class="form-group row" style="display:@if(old('frequency_per_day',$subactivity->frequency_per_day ?? '')==2)  @else none @endif;" id="frequency">
    <label for="inputEmail3" class="col-sm-3 col-form-label">Frequency</label>
    <div class="col-sm-9">
      <input type="text" name="frequency" class="form-control @error('frequency') is-invalid @enderror" id="inputEmail3" placeholder="Type Subactivty Name here..." value=" {{ old('frequency',$subactivity->frequency ?? '') }}">
      @error('frequency')
      <div class="invalid-feedback d-block">
          {{$message}}
      </div>
     @enderror
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3"></label>
    <div class="col-sm-9">
      <button type="submit" class="btn btn-primary">Submit</button>
      <a href="{{ route('subactivity.list') }}" class="btn btn-danger">Cancel</a>
    </div>
  </div>
</form>
                                </div>
                            </div>

                        </div>

                    </div>
@endsection('content')

@push('scripts')
<script src="{{ asset('assets/js/custom/subactivity/add.js') }}"></script>
@endpush  

resources/views/subactivity/list.blade.php
@extends('layouts.master')

@section('content')
    

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Subactivity</h1>



                    </div>

                    <div class="row">

                                 <div class="col-lg-12">
                          @if(session('message'))
                          <div class="alert alert-success"> 
                          {{ session('message') }}
                          </div>
                          @endif
                            <!-- Dropdown Card Example -->
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div
                                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                    <h6 class="m-0 font-weight-bold text-primary">Subactivities List</h6>
                                    <div class="dropdown no-arrow">
                                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                                            aria-labelledby="dropdownMenuLink">
                                            <div class="dropdown-header">ACM actions:</div>
                                            <a class="dropdown-item" href="{{ route('subactivity.add') }}">
                                            <i class="fas fa-plus"></i>
                                            Add New
                                            </a>
                                            <a class="dropdown-item" href="#">
                                            <i class="fas fa-sort"></i>
                                            Set sorting
                                            </a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">
                                            <i class="fas fa-times"></i>
                                            Close
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <!-- Card Body -->
                                <div class="card-body">
                                      <div class="table-responsive">
                                <table class="table table-bordered" id="" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Serial #</th>
                                            <th>
                                            <form action="{{ route('subactivity.list') }}" method="get">

                                                <label>Activity Models</label>
                                                <select name="activity_model" class="form-control" id="acms_dd_filter" multiple>
                                                    @foreach($acms as $acm)
                                                    <option value="{{ $acm->id }}">{{ $acm->activity_model }}</option>
                                                    @endforeach
                                                </select>
                                                
                                                </form>
                                            </th>
                                            <th>    
                                                <form action="{{ route('subactivity.list') }}" method="get">
                                                <label>Subactivity</label>
                                                <input type="text" name="subactivity" class="form-control" />
                                                </form>
                                            </th>
                                            <th>AM Type</th>
                                            <th>Status</th>
                                            <th>Created at</th>
                                            <th>Actions</th>
                                        </tr> 
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Serial #</th>
                                             <th>Activity Models</th>
                                             <th>
                                                 <input type="" name="">
                                             </th>
                                            <th>AM Type</th>
                                            <th>Status</th>
                                            <th>Created at</th>
                                            <th>Actions</th>
                                        </tr>
                                    </tfoot>
                                      <tbody>
                                          @foreach($subacts as $index=>$subact)
                                          <tr>
                                          <td>{{ $index + $subacts->firstItem() }}</td>
                                          <td>
                                              @foreach($subact->activityModels as $acm)
                                              <span class="badge badge-primary"> {{ $acm->activity_model }} </span>
                                              @endforeach
                                          </td>
                                          <td>
                                              {{ $subact->subactivity }}
                                          </td>
                                          <td>
                                            {!! $subact->am_type==1 ? '<span class="badge badge-success">Todo</span>' : '<span class="badge badge-danger">Not Todo</span>'  !!}
                                          </td>
                                          <td>
                                            <input type="checkbox" class="bs-switch" _id="{{ $subact->id }}" data-onstyle="success" data-toggle="toggle" data-on="Active" data-off="Deactive" data-size="xs" {{ $subact->active==1?'checked':'' }} >
                                          </td>
                                          <td>
                                            {{ date('M-d h:i:s A',strtotime($subact->created_at)) }}
                                          </td>
                                          <td>  
                                            <a href="{{ route('subactivity.edit',$subact) }}" class='btn btn-primary'>
                                              <i class="fas fa-edit"></i>
                                              Edit
                                            </a>
                                            <form method="post" action="{{ route('subactivity.delete',$subact)}}" style="display: inline;">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class='btn btn-danger delete-subact'>
                                              <i class="fas fa-trash"></i>
                                              Delete
                                            </button>
                                            </form>
                                          </td>
                                          </tr>
                                          @endforeach

                                          @if(!$subacts->count())
                                          <tr>
                                              <td colspan="7">
                                                <center>
                                                  No data found
                                                  </center>
                                              </td>
                                          </tr>
                                          @endif
                                      </tbody>
                                </table>
                                {{ $subacts->appends(request()->query())->links() }}
                                
                            </div>
                                </div>
                            </div>

                        </div>

                    </div>

              

@endsection('content')

@push('scripts')
<script src="{{ asset('assets/js/custom/subactivity/list.js') }}"></script>
    <script type="text/javascript">
        GLOBAL_VARS.services['set_status_subact'] = '{{ route('subactivity.set.status.subact') }}'
         @if(session('swal_delete'))
          swal('{{ @session('swal_delete') }}', {
          icon: "success",
          });
         @endif
    </script>   
@endpush